permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
# markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# 作者信息
author: 
  name: algking
  email: alg_king@hotmail.com
  link: http://algking.github.com
  weibo: http://weibo.com/algking
  github: http://github.com/algking

# 站点信息
title: ErlangFan
description: algking的博客
url: http://algking.github.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://yansu-uploads.stor.sinaapp.com/imgs/gavatar.png
favicon: http://yansu-uploads.stor.sinaapp.com/imgs/favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: algking.github.com

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: php

# 首页除了最新文章外显示分类
cates: 
  - emacs
  - php
   
# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
